image: node:lts

cache:
  paths:
    - node_modules/

pages:
  before_script:
    # Install packages
    - npm install
  script:
    # Build application and move content to public folder
    - npm run build && export
    - mv out/* public
  after_script:
    # Cleanup
    - rm -rf out
  artifacts:
    paths:
      - public
  only:
    - main
